c_gunicorn_tcp: Use *OWNER adopted authority
When starting TCP servers via STRTCP command, *AUTOSTART servers
are started under QTCP user profile which most likely doesn't have
sufficient authority to the user profile the server will be started
under and the SBMJOB will fail.

Instead use *OWNER adopted authority to ensure no matter who runs
the command it has sufficient authority to run. Echo a command as
an example to run if the user profile building the code doesn't have
sufficient authority either.

diff --git a/main/c_generic_server/setup b/main/c_generic_server/setup
--- a/main/c_generic_server/setup
+++ b/main/c_generic_server/setup
@@ -1,13 +1,17 @@
 #!/QOpenSys/usr/bin/ksh
 
+# exit immediately if command returns non-zero rc
 set -e
 
 TARGET=${TARGET:-OSSILE}
 
-system -kpieb "CRTCMOD MODULE(${TARGET}/GENERICTCP) SRCSTMF('$PWD/generic_tcp.c') DEFINE('__cplusplus__strings__') SYSIFCOPT(*IFS64IO) TERASPACE(*YES *TSIFC) INCDIR('$PWD/../c_inih/inih')"
+system -kpieb "CRTCMOD MODULE(${TARGET}/GENERICTCP) SRCSTMF('${PWD}/generic_tcp.c') DEFINE('__cplusplus__strings__') SYSIFCOPT(*IFS64IO) TERASPACE(*YES *TSIFC) INCDIR('${PWD}/../c_inih/inih')"
 
-system -kpieb "CRTPGM PGM(${TARGET}/GENERICTCP) MODULE(${TARGET}/GENERICTCP) BNDSRVPGM(${TARGET}/INIH) TEXT('STRTCPSVR *GENERIC processing program')"
-RC=$?
+system -kpieb "DLTPGM PGM(${TARGET}/GENERICTCP)" || :
+
+system -kpieb "CRTPGM PGM(${TARGET}/GENERICTCP) MODULE(${TARGET}/GENERICTCP) BNDSRVPGM(${TARGET}/INIH) USRPRF(*OWNER) TEXT('STRTCPSVR *GENERIC processing program')"
 
 echo "run ADDTCPSVR SVRSPCVAL(*GENERIC) PGM(${TARGET}/GENERICTCP) SVRNAME(GENERIC) SVRTYPE(GENERIC) TEXT('Generic TCP application server')"
-exit $RC
+echo
+echo "Ensure that ${TARGET}/GENERICTCP is owned by profile with sufficient authority to submit jobs under the users defined in the ini."
+echo "eg. CHGOBJOWN OBJ(${TARGET}/GENERICTCP) OBJTYPE(*PGM) NEWOWN(QSYS) CUROWNAUT(*SAME)"
diff --git a/main/c_gunicorn_server/setup b/main/c_gunicorn_server/setup
--- a/main/c_gunicorn_server/setup
+++ b/main/c_gunicorn_server/setup
@@ -1,14 +1,17 @@
-#!/QOpenSys/usr/bin/sh
+#!/QOpenSys/usr/bin/ksh
 
+# exit immediately if command returns non-zero rc
 set -e
 
 TARGET=${TARGET:-OSSILE}
 
-system -kpieb "CRTCMOD MODULE($TARGET/INIH) SRCSTMF('$PWD/inih/ini.c') SYSIFCOPT(*IFS64IO) TERASPACE(*YES *TSIFC) INCDIR('$PWD/inih')"
-system -kpieb "CRTCMOD MODULE($TARGET/GUNICRNTCP) SRCSTMF('$PWD/gunicorn_tcp.c') DEFINE('__cplusplus__strings__') SYSIFCOPT(*IFS64IO) TERASPACE(*YES *TSIFC) INCDIR('$PWD/../c_inih/inih')"
+system -kpieb "CRTCMOD MODULE(${TARGET}/GUNICRNTCP) SRCSTMF('${PWD}/gunicorn_tcp.c') DEFINE('__cplusplus__strings__') SYSIFCOPT(*IFS64IO) TERASPACE(*YES *TSIFC) INCDIR('${PWD}/../c_inih/inih')"
 
-system -kpieb "CRTPGM PGM($TARGET/GUNICRNTCP) MODULE($TARGET/GUNICRNTCP) BNDSRVPGM(${TARGET}/INIH) TEXT('STRTCPSVR *GUNICORN processing program')"
-RC=$?
+system -kpieb "DLTPGM PGM(${TARGET}/GUNICRNTCP)" || :
 
-echo "run ADDTCPSVR SVRSPCVAL(*GUNICORN) PGM($TARGET/GUNICRNTCP) SVRNAME(GUNICORN) SVRTYPE(GUNICORN) TEXT('Python gunicorn application server')"
-exit $RC
+system -kpieb "CRTPGM PGM(${TARGET}/GUNICRNTCP) MODULE(${TARGET}/GUNICRNTCP) BNDSRVPGM(${TARGET}/INIH) USRPRF(*OWNER) TEXT('STRTCPSVR *GUNICORN processing program')"
+
+echo "run ADDTCPSVR SVRSPCVAL(*GUNICORN) PGM(${TARGET}/GUNICRNTCP) SVRNAME(GUNICORN) SVRTYPE(GUNICORN) TEXT('Python gunicorn application server')"
+echo
+echo "Ensure that ${TARGET}/GUNICRNTCP is owned by profile with sufficient authority to submit jobs under the users defined in the ini."
+echo "eg. CHGOBJOWN OBJ(${TARGET}/GUNICRNTCP) OBJTYPE(*PGM) NEWOWN(QSYS) CUROWNAUT(*SAME)"
